name: Build Docker Images
on:
    push:
        branches:
            - main
jobs:
    checkout-build-push:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Build Docker Image
              run: |
                docker build -t ghcr.io/nreeazz/aplikasi-laravel  ./laravel
            - name: Login 
              run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u nreeazz --password-stdin
            - name: push
              run: docker push ghcr.io/nreeazz/aplikasi-laravel 